version: '3'
services:
  prefect:
    image: prefecthq/prefect:2-latest
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_URL=http://0.0.0.0:4200/api
    volumes:
      - prefect_data:/root/.prefect
    command: prefect server start --host 0.0.0.0

volumes:
  prefect_data: